/*
 * This Kotlin source file was generated by the Gradle "init" task.
 */
package io.github.llh4github.app

import org.junit.jupiter.api.Test

import org.junit.jupiter.api.Assertions.assertEquals

class MessageUtilsTest {
    @Test fun testGetMessage() {
    }
}
