# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package
on: workflow_dispatch
#on:
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Decode
      run: |
        echo "GPG_SECRET_KEY  ${{secrets.GPG_SECRET_KEY}}"
        echo "${{secrets.SIGNING_SECRET_KEY_RING_FILE}}" > ~/.gradle/secring.gpg.base64
        base64 -d ~/.gradle/secring.gpg.base64 > ~/.gradle/secring.gpg
    - name: Assemble the Project
      run: ./gradlew assemble
      
    - name: Publish Artifacts
      run: |
        if [[ $(cat "project.version") =~ "SNAPSHOT" ]] ; then
          ./gradlew publishDistPublicationToSnapshotRepository -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
        else
          if [[ $GITHUB_EVENT_NAME == "release" ]] ; then
            ./gradlew publishDistPublicationToCentralRepository -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
          else
            echo "Skip release publication because this is not a release event"
          fi
        fi
      env:
        OSSRH_USER: ${{secrets.OSSRH_USER}}
        OSSRH_PASSWORD: ${{secrets.OSSRH_PASSWORD}}
        GPG_KEY_ID: ${{secrets.GPG_KEY_ID}}
        GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}
#        GPG_SECRET_KEY: ${{secrets.GPG_SECRET_KEY}}
        GPG_SECRET_KEY: ${{secrets.GPG_SECRET_KEY}}
